# Generated by Django 4.2.1 on 2023-06-01 14:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_car'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=100)),
                ('lname', models.CharField(max_length=100)),
                ('t_type', models.CharField(choices=[('Bought', 'Bought'), ('Repair', 'Repair'), ('Consult', 'Consult')], max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('t_status', models.CharField(choices=[('Fully paid', 'Fully paid'), ('Partially paid', 'Partially paid'), ('NA', 'NA')], max_length=50)),
                ('date', models.DateField()),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employees.car')),
            ],
        ),
    ]
